# on:
#   schedule:
#     - cron: '0 12 * * *'
#   push:
#     branches:
#       - main

on: push

jobs:
  bulid:
    runs-on: ubuntu-latest
    env:
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      FROM_EMAIL_PASSWORD: ${{ secrets.FROM_EMAIL_PASSWORD }}
      TO_EMAIL: ${{secrets.TO_EMAIL}}
      REPOSITORY_ACCESS_KEY: ${{ secrets.REPOSITORY_ACCESS_KEY }}
      USER_NAME: ${{ secrets.USER_NAME }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install
      - run: npm start
