on:
  schedule:
    - cron: '10 19 * * *'

jobs:
  bulid:
    runs-on: ubuntu-latest
    env:
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REPOSITORY_ACCESS_KEY: ${{ secrets.REPOSITORY_ACCESS_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install
      - run: npm start
